### ISSUE TITLE
Local Labels that start with : don't work

### ISSUE THREAD

**Issue by dwsJason** [Sakrac/x65#2]
Example lst output below:
$000a e2 30       sep #$30       3               sep #$30
asm/waitkey.s(33):
$000c 8f 10 c0 e0 sta $e0c010    5+              stal $e0c010
                                        :lp
$0010 af 00 c0 e0 lda $e0c000    5+              ldal $e0c000
                                                 bpl :lp
$0014 8f 10 c0 e0 sta $e0c010    5+              stal $e0c010

I have verified that if I swap the :lp lable, with .lp, that code does generate for the bpl :lp

I am using the linker if that makes any difference.   Generating a GSOS application.  Basically I noticed this because the program wasn't waiting for my key-press.

**Comment by Sakrac** [comment]
Totally forgot I support : for local labels! Turns out I added support for Kick Assembler syntax which conflicts with this. I can add a command line option for that to disambiguate and allow ':' for local labels again.

**Comment by Sakrac** [comment]
Fixed, if for any reason Kick Assembler code with macros are needed this can be disabled by passing in -KickAsm as a command line argument.

**Comment by dwsJason** [comment]
Confirmed Fixed.
